package com.base.noob.ray.noob.database.mapper;


import com.base.noob.ray.noob.database.dto.NoobConfig;
import com.base.noob.ray.noob.database.dto.NoobConfigCriteria;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class NoobConfigSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String countByExample(NoobConfigCriteria example) {
        BEGIN();
        SELECT("count(*)");
        FROM("noob_config");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String deleteByExample(NoobConfigCriteria example) {
        BEGIN();
        DELETE_FROM("noob_config");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String insertSelective(NoobConfig record) {
        BEGIN();
        INSERT_INTO("noob_config");
        
        if (record.getNoobApp() != null) {
            VALUES("noob_app", "#{noobApp,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobTag() != null) {
            VALUES("noob_tag", "#{noobTag,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobGroup() != null) {
            VALUES("noob_group", "#{noobGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getGmtTime() != null) {
            VALUES("gmt_time", "#{gmtTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModTime() != null) {
            VALUES("mod_time", "#{modTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String selectByExample(NoobConfigCriteria example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("noob_app");
        SELECT("noob_tag");
        SELECT("noob_group");
        SELECT("content");
        SELECT("status");
        SELECT("gmt_time");
        SELECT("mod_time");
        FROM("noob_config");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        NoobConfig record = (NoobConfig) parameter.get("record");
        NoobConfigCriteria example = (NoobConfigCriteria) parameter.get("example");
        
        BEGIN();
        UPDATE("noob_config");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getNoobApp() != null) {
            SET("noob_app = #{record.noobApp,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobTag() != null) {
            SET("noob_tag = #{record.noobTag,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobGroup() != null) {
            SET("noob_group = #{record.noobGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{record.status,jdbcType=INTEGER}");
        }
        
        if (record.getGmtTime() != null) {
            SET("gmt_time = #{record.gmtTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModTime() != null) {
            SET("mod_time = #{record.modTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("noob_config");
        
        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("noob_app = #{record.noobApp,jdbcType=VARCHAR}");
        SET("noob_tag = #{record.noobTag,jdbcType=VARCHAR}");
        SET("noob_group = #{record.noobGroup,jdbcType=VARCHAR}");
        SET("content = #{record.content,jdbcType=VARCHAR}");
        SET("status = #{record.status,jdbcType=INTEGER}");
        SET("gmt_time = #{record.gmtTime,jdbcType=TIMESTAMP}");
        SET("mod_time = #{record.modTime,jdbcType=TIMESTAMP}");
        
        NoobConfigCriteria example = (NoobConfigCriteria) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String updateByPrimaryKeySelective(NoobConfig record) {
        BEGIN();
        UPDATE("noob_config");
        
        if (record.getNoobApp() != null) {
            SET("noob_app = #{noobApp,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobTag() != null) {
            SET("noob_tag = #{noobTag,jdbcType=VARCHAR}");
        }
        
        if (record.getNoobGroup() != null) {
            SET("noob_group = #{noobGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getGmtTime() != null) {
            SET("gmt_time = #{gmtTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModTime() != null) {
            SET("mod_time = #{modTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected void applyWhere(NoobConfigCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<NoobConfigCriteria.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            NoobConfigCriteria.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<NoobConfigCriteria.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    NoobConfigCriteria.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}