package com.base.noob.ray.noob.database.mapper;


import com.base.noob.ray.noob.database.dto.NoobConfig;
import com.base.noob.ray.noob.database.dto.NoobConfigCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface NoobConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @SelectProvider(type=NoobConfigSqlProvider.class, method="countByExample")
    int countByExample(NoobConfigCriteria example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @DeleteProvider(type=NoobConfigSqlProvider.class, method="deleteByExample")
    int deleteByExample(NoobConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @Delete({
        "delete from noob_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @Insert({
        "insert into noob_config (noob_app, noob_tag, ",
        "noob_group, content, ",
        "status, gmt_time, ",
        "mod_time)",
        "values (#{noobApp,jdbcType=VARCHAR}, #{noobTag,jdbcType=VARCHAR}, ",
        "#{noobGroup,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{gmtTime,jdbcType=TIMESTAMP}, ",
        "#{modTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(NoobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @InsertProvider(type=NoobConfigSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(NoobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @SelectProvider(type=NoobConfigSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.BIGINT, id=true),
        @Result(column="noob_app", property="noobApp", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_tag", property="noobTag", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_group", property="noobGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="gmt_time", property="gmtTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mod_time", property="modTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<NoobConfig> selectByExampleWithRowbounds(NoobConfigCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @SelectProvider(type=NoobConfigSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="noob_app", property="noobApp", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_tag", property="noobTag", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_group", property="noobGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="gmt_time", property="gmtTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mod_time", property="modTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<NoobConfig> selectByExample(NoobConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @Select({
        "select",
        "id, noob_app, noob_tag, noob_group, content, status, gmt_time, mod_time",
        "from noob_config",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="noob_app", property="noobApp", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_tag", property="noobTag", jdbcType=JdbcType.VARCHAR),
        @Result(column="noob_group", property="noobGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="gmt_time", property="gmtTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mod_time", property="modTime", jdbcType=JdbcType.TIMESTAMP)
    })
    NoobConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @UpdateProvider(type=NoobConfigSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") NoobConfig record, @Param("example") NoobConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @UpdateProvider(type=NoobConfigSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") NoobConfig record, @Param("example") NoobConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @UpdateProvider(type=NoobConfigSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(NoobConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    @Update({
        "update noob_config",
        "set noob_app = #{noobApp,jdbcType=VARCHAR},",
          "noob_tag = #{noobTag,jdbcType=VARCHAR},",
          "noob_group = #{noobGroup,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "gmt_time = #{gmtTime,jdbcType=TIMESTAMP},",
          "mod_time = #{modTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(NoobConfig record);
}