package com.base.noob.ray.noob.database.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class NoobConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.id
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.noob_app
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private String noobApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.noob_tag
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private String noobTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.noob_group
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private String noobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.content
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.status
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.gmt_time
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private Date gmtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noob_config.mod_time
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

}