package com.base.noob.ray.noob.database.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NoobConfigCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public NoobConfigCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoobAppIsNull() {
            addCriterion("noob_app is null");
            return (Criteria) this;
        }

        public Criteria andNoobAppIsNotNull() {
            addCriterion("noob_app is not null");
            return (Criteria) this;
        }

        public Criteria andNoobAppEqualTo(String value) {
            addCriterion("noob_app =", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppNotEqualTo(String value) {
            addCriterion("noob_app <>", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppGreaterThan(String value) {
            addCriterion("noob_app >", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppGreaterThanOrEqualTo(String value) {
            addCriterion("noob_app >=", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppLessThan(String value) {
            addCriterion("noob_app <", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppLessThanOrEqualTo(String value) {
            addCriterion("noob_app <=", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppLike(String value) {
            addCriterion("noob_app like", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppNotLike(String value) {
            addCriterion("noob_app not like", value, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppIn(List<String> values) {
            addCriterion("noob_app in", values, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppNotIn(List<String> values) {
            addCriterion("noob_app not in", values, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppBetween(String value1, String value2) {
            addCriterion("noob_app between", value1, value2, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobAppNotBetween(String value1, String value2) {
            addCriterion("noob_app not between", value1, value2, "noobApp");
            return (Criteria) this;
        }

        public Criteria andNoobTagIsNull() {
            addCriterion("noob_tag is null");
            return (Criteria) this;
        }

        public Criteria andNoobTagIsNotNull() {
            addCriterion("noob_tag is not null");
            return (Criteria) this;
        }

        public Criteria andNoobTagEqualTo(String value) {
            addCriterion("noob_tag =", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagNotEqualTo(String value) {
            addCriterion("noob_tag <>", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagGreaterThan(String value) {
            addCriterion("noob_tag >", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagGreaterThanOrEqualTo(String value) {
            addCriterion("noob_tag >=", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagLessThan(String value) {
            addCriterion("noob_tag <", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagLessThanOrEqualTo(String value) {
            addCriterion("noob_tag <=", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagLike(String value) {
            addCriterion("noob_tag like", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagNotLike(String value) {
            addCriterion("noob_tag not like", value, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagIn(List<String> values) {
            addCriterion("noob_tag in", values, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagNotIn(List<String> values) {
            addCriterion("noob_tag not in", values, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagBetween(String value1, String value2) {
            addCriterion("noob_tag between", value1, value2, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobTagNotBetween(String value1, String value2) {
            addCriterion("noob_tag not between", value1, value2, "noobTag");
            return (Criteria) this;
        }

        public Criteria andNoobGroupIsNull() {
            addCriterion("noob_group is null");
            return (Criteria) this;
        }

        public Criteria andNoobGroupIsNotNull() {
            addCriterion("noob_group is not null");
            return (Criteria) this;
        }

        public Criteria andNoobGroupEqualTo(String value) {
            addCriterion("noob_group =", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupNotEqualTo(String value) {
            addCriterion("noob_group <>", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupGreaterThan(String value) {
            addCriterion("noob_group >", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupGreaterThanOrEqualTo(String value) {
            addCriterion("noob_group >=", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupLessThan(String value) {
            addCriterion("noob_group <", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupLessThanOrEqualTo(String value) {
            addCriterion("noob_group <=", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupLike(String value) {
            addCriterion("noob_group like", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupNotLike(String value) {
            addCriterion("noob_group not like", value, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupIn(List<String> values) {
            addCriterion("noob_group in", values, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupNotIn(List<String> values) {
            addCriterion("noob_group not in", values, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupBetween(String value1, String value2) {
            addCriterion("noob_group between", value1, value2, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andNoobGroupNotBetween(String value1, String value2) {
            addCriterion("noob_group not between", value1, value2, "noobGroup");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGmtTimeIsNull() {
            addCriterion("gmt_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtTimeIsNotNull() {
            addCriterion("gmt_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtTimeEqualTo(Date value) {
            addCriterion("gmt_time =", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeNotEqualTo(Date value) {
            addCriterion("gmt_time <>", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeGreaterThan(Date value) {
            addCriterion("gmt_time >", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_time >=", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeLessThan(Date value) {
            addCriterion("gmt_time <", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_time <=", value, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeIn(List<Date> values) {
            addCriterion("gmt_time in", values, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeNotIn(List<Date> values) {
            addCriterion("gmt_time not in", values, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_time between", value1, value2, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andGmtTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_time not between", value1, value2, "gmtTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("mod_time is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("mod_time is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("mod_time =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("mod_time <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("mod_time >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mod_time >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("mod_time <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("mod_time <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("mod_time in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("mod_time not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("mod_time between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("mod_time not between", value1, value2, "modTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table noob_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 28 14:41:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table noob_config
     *
     * @mbggenerated Thu Sep 28 14:41:51 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}